services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: baas
      MYSQL_PASSWORD: baas
      MYSQL_DATABASE: baas
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - baas-network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - baas-network

volumes:
  mysql-volume:
    driver: local

networks: 
  baas-network:
    driver: bridge